CREATE USER boletia;
ALTER USER boletia WITH SUPERUSER;
ALTER USER boletia WITH LOGIN;
ALTER USER boletia WITH PASSWORD '123456';


CREATE USER axel;
ALTER USER axel WITH SUPERUSER;
ALTER USER axel WITH LOGIN;
ALTER USER axel WITH PASSWORD '123456';